# -*- coding: utf-8 -*-
"""Huggingface-Beispiel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1heKGh3_0uRhKpQOyl5SQIypSggPx7nnf
"""

!pip install transformers
!pip install huggingface_hub
!pip install accelerate

import torch
from transformers import pipeline

summarizer = pipeline('summarization')

wikipedia_text = """Die Triodos Bank N.V. ist eine Aktiengesellschaft niederländischen Rechts mit Hauptsitz in Zeist, Niederlande.[5] Sie umfasst Zweigniederlassungen und Repräsentanzen in sechs europäischen Ländern,[4] sowie die Tochterunternehmen Triodos Investment Management und Triodos Private Banking.[6] Zusammen bietet die Triodos Gruppe ein breites Spektrum an Dienstleistungen an: Bankdienstleistungen, Fondsmanagement, Projektentwicklung, Depotgeschäft, Beteiligungskapital, Unternehmensfinanzierung und Private Banking.[7][8]
Zum 31. Dezember 2015 betrug das Geschäftsvolumen der Triodos Bankengruppe rund 12,3 Milliarden Euro,[4] sie vergab über 44.000 (2015) Kredite[4] und betreute in Europa über 700.000 Kundenkonten.[4]
Die Triodos Bank wurde von der Financial Times und der Internationalen Finanz-Corporation (IFC), einer Organisation der Weltbank, mit dem Award „Sustainable Bank of the Year 2009“ ausgezeichnet. Sie wurde unter 165 Instituten aus 42 Ländern ausgewählt.[9]
Stiftung zur Verwaltung der Aktien der Triodos Bank (SAAT)
Die Stiftung zur Verwaltung der Aktien der Triodos (niederl.: Stichting Administratiekantoor Aandelen Triodos Bank/SAAT[10]) verwaltet die Aktien der Bank.[11] Privatpersonen und institutionelle Investoren, die sich an der Bank beteiligen wollen, können sogenannte Aktienähnliche Rechte über die Stiftung erwerben.[11][12] Kein Eigner dieser Aktienähnlichen Rechte ist jedoch befugt, mehr als 10 % der Unternehmensanteile zu halten und das Stimmrecht ist auf 1000 Stimmen begrenzt. Zu den größten Aktionären der Triodos Bank zählen gegenwärtig Coöperatieve Centrale Raiffeisen-Boerenleenbank BA und Delta Lloyd Levensverzekering N.V.
Philosophie
Für die Gründer der Triodos Bank war das anthroposophische Prinzip eine Inspirationsquelle, ist nach eigenen Angaben jedoch kein relevantes Kriterium mehr.[13]
„Die Triodos Bank ist eine wertebasierte Bank, die sich von ihrer Mission leiten lässt, Geld bewusst einzusetzen, um positive Veränderungen in der Gesellschaft und der Umwelt zu fördern, wobei die Menschenwürde im Mittelpunkt steht. Die Bank lehnt jede Form der Diskriminierung ab, weil sie nicht den Kernwerten der Bank entspricht. Daher hält die Triodos Bank mehrere Aussagen Rudolf Steiners, dem Begründer der Anthroposophie, über Rassen für inakzeptabel, weil sie suggerieren, dass die Menschen nicht gleich sind. Dies widerspricht diametral den Werten der Bank. Von diesen rassistischen Aussagen distanziert sich die Bank ausdrücklich. Diese Aussagen werden auch von Anthroposoph:innen als nicht erträglich eingestuft.“[13]
Die Einlagen ihrer Kunden vergibt die Bank ausschließlich an die Realwirtschaft[14] und finanziert dabei Unternehmen, Organisationen und Projekte, die nach ihrer Ansicht zu einem ökologischen, sozialen oder kulturellen Wandel beitragen.[15] Gemäß dieser Philosophie bezieht die Triodos Bank in Deutschland Strom vom Ökoenergieanbieter Naturstrom AG.[16]
Geschichte
Im Jahre 1968 beschlossen Adriaan Deking Dura (Wirtschaftswissenschaftler), Dieter Brüll (Professor für Steuerrecht), Lex Bos (Unternehmensberater) und Rudolf Mees (Bankkaufmann) in den Niederlanden ein Modell zur nachhaltigen Verwaltung von Geld zu entwickeln.[17] Aus diesem Zusammenschluss entstanden 1971 die Triodos Stiftung (SAAT) und 1980 die unabhängige Triodos Bank N.V. Seither hat die Bank nachhaltige Entwicklung mitgeprägt und vorangetrieben. Als eine der ersten Banken investierte sie in erneuerbare Energien. 1990 legte sie über Triodos Investment Management erstmals Fonds auf. Im Laufe der 1990er Jahre wurden Mikrofinanzfonds für Entwicklungsländer eingeführt.[17] Die Bank erweiterte ihr Fondsportfolio um die Bereiche Fairer Handel, SRI (Socially Responsible Investment), Immobilien und Kultur.[17] Derzeit bietet die Bank u. a. Fonds in den Bereichen erneuerbare Energien, SRI und Mikrofinanz an.[18] In den 1990er Jahren weitete die Triodos Bank mit der Eröffnung einer belgischen und englischen Niederlassung ihre Geschäftstätigkeit aus. 2004 nahm in Spanien eine weitere Niederlassung die Arbeit auf und 2009 öffnete die Triodos Bank auch in Deutschland, in Frankfurt am Main, eine Niederlassung.[17] 2013 wurde zudem eine neue Vertretung der Triodos Bank in Frankreich eröffnet.[4]
"""
result = summarizer(wikipedia_text, max_length=150, min_length=30)

result[0]["summary_text"]

sentiment = pipeline('sentiment-analysis')

text = ('I loved it', 'I hated the service','Es war so lala')
sentiment_result = sentiment(text)

for r, t in zip(sentiment_result, text):
  print(t, '-->', r['label'])

translator = pipeline('translation', model="Helsinki-NLP/opus-mt-en-fr")

translator(result[0]['summary_text '])

